### PR TITLE
Add `blocked` state to table

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Review by perlpunk — CHANGES_REQUESTED** [review]
It also needs to be added to `.github/workflows/backlog_checker.yml`

**Comment by mimi1vx** [comment]
> Where does this query come from? I'm not sure if we should care about such limit here

maybe not care about limit , but is pretty useable to see how much of our backlog is in blocked state and waiting for something else

**Comment by mimi1vx** [comment]
.. I'm not able create public query :( @perlpunk  thx for notify ..

**Comment by kalikiana** [comment]
> .. I'm not able create public query :( @perlpunk thx for notify ..

What is it that you wanted to add? Usually we use save queries that we've tested and [documented on the wiki](https://progress.opensuse.org/projects/qa/wiki/Tools#How-we-work-on-our-backlog).

**Comment by okurz** [comment]
> maybe not care about limit , but is pretty useable to see how much of our backlog is in blocked state and waiting for something else

oh, I see. Yes. IMHO such limits can found on https://progress.opensuse.org/issues/?query_id=230 easily especially when collapsing the individual group of tickets for each status. The main goal of https://os-autoinst.github.io/qa-tools-backlog-assistant/ is – or at least so far was – to have actual checks with their limits displayed

**Pull request closed without merging**
