### PR TITLE
Use sys.exit() over exit()

### PR DESCRIPTION
**Pull request by alanyee**
Use `sys.exit()` over `exit()` as `exit()` is to be used in the "interactive interpreter shell and should not be used in programs."

Source: https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module

### CODE REVIEW

**Comment by okurz** [comment]
Hi, the problem with the recurring updates in the master branch are fixed by https://github.com/os-autoinst/qa-tools-backlog-assistant/pull/15 . If you are still interested, please rebase your branch on current master and update the pull request. Thank you!

**Comment by perlpunk** [comment]
please wait until #20 is merged!

**Review by okurz — CHANGES_REQUESTED** [review]
needs rebase

**Comment by alanyee** [comment]
That's interesting. The PR closed when I rebase and force pushed.

**Pull request closed without merging**
