### PR TITLE
Re-introduce Closed yesterday w/o min or max

### PR DESCRIPTION
**Pull request by kalikiana**
See: https://progress.opensuse.org/issues/121582

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
Why do we need the query on the generated page at all?

**Comment by perlpunk** [comment]
> Why do we need the query on the generated page at all?

Why didn't you ask that question on the [backlogger PR](https://github.com/openSUSE/backlogger/pull/19) instead of blocking that change now?
The longer we block to get in that query, the longer we aren't collecting data, so finishing of the ticket will be delayed.

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
> Why do we need the query on the generated page at all?

We could leave out queries that have no min and max from the generated page completely. That was actually how I suggested it. But we can figure that out later

**Comment by okurz** [comment]
> > Why do we need the query on the generated page at all?
> 
> Why didn't you ask that question on the [backlogger PR](https://github.com/openSUSE/backlogger/pull/19) instead of blocking that change now?

Because I am behind with reviewing code and I have a sick child at home and I couldn't review that PR which was merged even within one day (~12h) which is great to see moving that quickly but then please understand that I didn't manage to comment there.

I guess I am not understanding that part of backlogger implementation but apparently it's designed to include queries that one wants to include in the status page. But if we don't want it on the status page, again, why do we need the query on the generated page at all?

**Comment by kalikiana** [comment]
> I guess I am not understanding that part of backlogger implementation but apparently it's designed to include queries that one wants to include in the status page. But if we don't want it on the status page, again, why do we need the query on the generated page at all?

We never decided one way or the other. I simply left it because that's the least surprising behavior to anyone configuring the queries in YAML.

**Comment by okurz** [comment]
Yeah but why do we need to add queries to backlogger initially when we don't want to see anything on the status page? I feel we are abusing backlogger to "get data into grafana" when I am not convinced it shoud do that

**Comment by perlpunk** [comment]
How about using two different `queries.yaml` actually? We already push unneeded data into influxdb, e.g. we have all the ticket counts of In Progress, Workable etc. twice.
We should discuss this together.
But maybe do this afterwards and just merge this now.

**Review by okurz — APPROVED** [review]
Agreed

**Comment by kalikiana** [comment]
> Yeah but why do we need to add queries to backlogger initially when we don't want to see anything on the status page? I feel we are abusing backlogger to "get data into grafana" when I am not convinced it shoud do that

We want to "see" the results of the same queries in both output modes. Obviously with openSUSE/backlogger#20 that's going to be a lot less true.

**Comment by okurz** [comment]
> > Yeah but why do we need to add queries to backlogger initially when we don't want to see anything on the status page? I feel we are abusing backlogger to "get data into grafana" when I am not convinced it shoud do that
> 
> We want to "see" the results of the same queries in both output modes. Obviously with [openSUSE/backlogger#20](https://github.com/openSUSE/backlogger/pull/20) that's going to be a lot less true.

how about a flog on each query to decide in which output mode to include, e.g.

```
output=all
output=markdown
output=influxdb
```

**Comment by perlpunk** [comment]
> ```
> output=all
> output=markdown
> output=influxdb
> ```


> ```
> output: [markdown, influxdb]
> output: markdown
> output: influxdb
> ```

**Pull request merged**
