### PR TITLE
Prevent conflicts in master by pushing to gh-pages instead

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by perlpunk** [comment]
Maybe we could also create an SVG of the table, and that can then be included in the README. :]

**Review by kalikiana — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Comment by okurz** [comment]
I don't understand why this still or again receives changes. I thought we managed to prevent them with https://github.com/os-autoinst/qa-tools-backlog-assistant/blob/master/.github/workflows/backlog_checker.yml#L11 , strange

**Comment by perlpunk** [comment]
> I don't understand why this still or again receives changes.

The master branch in the origin repo is changed, that's what the message is about:
```
github-actions bot force-pushed the master branch 30 times, most recently from fda8029 to 0624165 2 minutes ago
```
I assume if a PR targets master, then every force push will result in such a notification.
This PR should fix it.

**Comment by okurz** [comment]
Well, let's try

**Pull request merged**
